name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 15 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print echos
        run: |
          echo "Job triggered ${{ github.event_name }}"
          echo "Repository ${{ github.repository }}"
          echo "Branch name ${{ github.ref }}"
      - uses: actions/checkout@v4.2.2
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: testing
    steps:
      - run: echo "Testing..."
  load-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: load-test
    steps:
      - run: |
          echo "Load testing..."
          sleep 5
  production:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment:
      name: production
      url: https://github.com
    steps:
      - run: |
          echo "Production deployment..."
          sleep 5
          echo "The environment is ${{ github.event.inputs.environment }}"
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The branch is ${{ github.ref }} and the repository is ${{ github.repository }}"