name: Reuse Workflow
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      name: 'John Helldiver'
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - name: Use output
        run: echo "The greeting was made at ${{ needs.call-workflow.outputs.time }}"